//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 4.1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Alpha;

namespace Alpha_Model.Screens
{
	public partial class  TestScreen1 : BaseScreen
	{
		public  TestScreen1(IAppBasics appBasics) : base(appBasics, "Test Screen 1", Images.TestScreen1.Screen_Loaded)
		{
			SwitchButton = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Switch Button", activeImageReference: Images.TestScreen1.SwitchButton.active, inactiveImageReference: Images.TestScreen1.SwitchButton.inactive, filters: ScreenSelect) { ParentScreen = this }; 
			ReferenceToExistingImage = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Reference to existing image", imageReference: Images.ImageForSwModel, filters: ScreenSelect) { ParentScreen = this }; 
			TextLabel = new Progile.TRIO.BaseModel.LabelWithCheckbox(tester: t, displayName: "Text Label", checkboxPosition: RelativePosition.Right, searchTextForLabel: "Static Test Image", checkedImageReference: Images.TestScreen1.TextLabel.Checkbox._checked, uncheckedImageReference: Images.TestScreen1.TextLabel.Checkbox._unchecked, checkboxLineHeight: 150, filters: ScreenSelect) { ParentScreen = this }; 
			
			ConfigureElementProperties();
        }

		  
		public Progile.TRIO.BaseModel.Button SwitchButton { get; private set; }
		  
		public Progile.TRIO.BaseModel.Label ReferenceToExistingImage { get; private set; }
		  
		public Progile.TRIO.BaseModel.LabelWithCheckbox TextLabel { get; private set; }
		
		partial void ConfigureElementProperties();
	}
}