//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.7.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Alpha;

namespace Alpha_Model.Screens
{
    [Screen]
    public partial class TestScreen1 : Progile.TRIO.BaseModel.BaseScreen
    {
        public TestScreen1(AlphaApp app) : base(app, @"Test Screen 1", Images.TestScreen1.Screen_Loaded)
        {
            App = app;
            SwitchButton = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Switch Button", activeImageReference: Images.TestScreen1.SwitchButton.active, inactiveImageReference: Images.TestScreen1.SwitchButton.inactive, filters: ScreenSelect) { ParentElement = this };
            ReferenceToExistingImage = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Reference to existing image", imageReference: Images.ImageForSwModel, filters: ScreenSelect) { ParentElement = this };
            TextLabel = new Progile.TRIO.BaseModel.LabelWithCheckbox(tester: t, displayName: "Text Label", checkboxPosition: RelativePosition.Right, searchTextForLabel: "Static Test Image", checkedImageReference: Images.TestScreen1.TextLabel.Checkbox._checked, uncheckedImageReference: Images.TestScreen1.TextLabel.Checkbox._unchecked, checkboxLineHeight: 150, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private AlphaApp App { get; set; }
        public Progile.TRIO.BaseModel.Button SwitchButton { get; private set; }

        public Progile.TRIO.BaseModel.Label ReferenceToExistingImage { get; private set; }

        public Progile.TRIO.BaseModel.LabelWithCheckbox TextLabel { get; private set; }

        partial void ConfigureElementProperties();
    }
}